FROM node:14-alpine as compiler
WORKDIR /usr/app

COPY package*.json .
COPY Gruntfile.js .
COPY next.config.js .

COPY components components
COPY data data
COPY fragments fragments
COPY pages pages
COPY public public
COPY styles styles

RUN npm install && npm install -g grunt-cli
RUN npm run export
RUN grunt