FROM node:14-alpine as compiler
WORKDIR /usr/app

COPY package*.json ./
COPY Gruntfile.js ./
COPY next.config.js ./

RUN npm install && npm install -g grunt-cli

COPY components components
COPY data data
COPY fragments fragments
COPY pages pages
COPY public public
COPY styles styles

RUN npm run export
RUN grunt