FROM node:16-alpine as compiler
WORKDIR /usr/app

COPY package*.json ./
COPY tsconfig.json ./
COPY Gruntfile.js ./
COPY next.config.js ./
COPY .eslintrc.json ./

RUN npm install && npm install -g grunt-cli

COPY layouts layouts
COPY components components
COPY data data
COPY pages pages
COPY public public
COPY styles styles
COPY interfaces interfaces

RUN npm run export
RUN grunt