FROM nginx-with-brotli
RUN rm -rf /usr/share/nginx/html/*
COPY --from=compiler /usr/app/out /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]